//
// Card.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Card: Codable {

    public var image: String
    public var value: String
    public var suit: String
    public var code: String

    public init(image: String, value: String, suit: String, code: String) {
        self.image = image
        self.value = value
        self.suit = suit
        self.code = code
    }


}

