//
// Cards.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Cards: Codable {

    public var cards: [Card]

    public init(cards: [Card]) {
        self.cards = cards
    }


}

